# Config file for automatic testing at travis-ci.org

# Only test master and pull requests; skip tags.
# Other branches can allow themselves.
branches:
  only:
    - master

# Prefer docker containers
sudo: required

language: python

python:
  - "3.6"

cache: pip

addons:
  apt:
    packages:
      - python-psycopg2
      - python3-psycopg2
  postgresql: "9.4"

env:
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=py36
  - TOXENV=py27-postgres
  - TOXENV=py34-postgres
  - TOXENV=py35-postgres
  - TOXENV=py36-postgres
  - TOXENV=py27-sqlite
  - TOXENV=py34-sqlite
  - TOXENV=py35-sqlite
  - TOXENV=py36-sqlite
  - TOXENV=py27-flake8
  - TOXENV=py34-flake8

install:
  - travis_retry pip install tox

script:
  - tox
