os: linux

dist: xenial

language: python

python:
  - "2.7"

cache: pip

addons:
  apt:
    packages:
      - python-psycopg2
      - python3-psycopg2
  postgresql: "9.4"

matrix:
  include:
  - python: "2.7"
    env: TOXENV=py27
  - python: "3.4"
    env: TOXENV=py34
  - python: "3.5"
    env: TOXENV=py35
  - python: "3.6"
    env: TOXENV=py36
  - python: "3.7"
    env: TOXENV=py37
  - python: "3.8"
    env: TOXENV=py38
  - python: "2.7"
    env: TOXENV=py27-postgres
  - python: "3.4"
    env: TOXENV=py34-postgres
  - python: "3.5"
    env: TOXENV=py35-postgres
  - python: "3.6"
    env: TOXENV=py36-postgres
  - python: "3.7"
    env: TOXENV=py37-postgres
  - python: "3.8"
    env: TOXENV=py38-postgres
  - python: "2.7"
    env: TOXENV=py27-sqlite
  - python: "3.4"
    env: TOXENV=py34-sqlite
  - python: "3.5"
    env: TOXENV=py35-sqlite
  - python: "3.6"
    env: TOXENV=py36-sqlite
  - python: "3.7"
    env: TOXENV=py37-sqlite
  - python: "3.8"
    env: TOXENV=py38-sqlite
  - python: "2.7"
    env: TOXENV=py27-flake8
  - python: "3.8"
    env: TOXENV=py38-flake8

install:
  - travis_retry pip install --upgrade "pip < 19.1" setuptools tox ppu

script:
  - tox

before_cache:
  - remove-old-files.py -o 180 ~/.cache/pip
