# Test on windows
# Heavily inspired by Oliver Grisel's appveyor-demo (https://github.com/ogrisel/python-appveyor-demo)
version: '{branch}-{build}'

# Only test master and pull requests; skip tags.
# Other branches can allow themselves.
branches:
  only:
    - master
skip_branch_with_pr: false
skip_tags: true

cache:
  - '%LOCALAPPDATA%\pip\Cache'

# Match travis
clone_depth: 50

services:
  - postgresql

environment:
  PGUSER: "postgres"
  PGPASSWORD: "Password12!"

  matrix:
    - TOX_ENV: "py27"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"
      PYTHON_HOME: "C:\\Python27"
    - TOX_ENV: "py27"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"
      PYTHON_HOME: "C:\\Python27-x64"
    - TOX_ENV: "py34"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "32"
      PYTHON_HOME: "C:\\Python34"
    - TOX_ENV: "py34"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "64"
      PYTHON_HOME: "C:\\Python34-x64"
    - TOX_ENV: "py35"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "32"
      PYTHON_HOME: "C:\\Python35"
    - TOX_ENV: "py35"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"
      PYTHON_HOME: "C:\\Python35-x64"
    - TOX_ENV: "py36"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "32"
      PYTHON_HOME: "C:\\Python36"
    - TOX_ENV: "py36"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
      PYTHON_HOME: "C:\\Python36-x64"
    - TOX_ENV: "py27-postgres-w32"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"
      PYTHON_HOME: "C:\\Python27"
    - TOX_ENV: "py27-postgres-w32"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"
      PYTHON_HOME: "C:\\Python27-x64"
    - TOX_ENV: "py34-postgres-w32"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "32"
      PYTHON_HOME: "C:\\Python34"
    - TOX_ENV: "py34-postgres-w32"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "64"
      PYTHON_HOME: "C:\\Python34-x64"
    - TOX_ENV: "py35-postgres-w32"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "32"
      PYTHON_HOME: "C:\\Python35"
    - TOX_ENV: "py35-postgres-w32"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"
      PYTHON_HOME: "C:\\Python35-x64"
    - TOX_ENV: "py36-postgres-w32"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "32"
      PYTHON_HOME: "C:\\Python36"
    - TOX_ENV: "py36-postgres-w32"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
      PYTHON_HOME: "C:\\Python36-x64"
    - TOX_ENV: "py27-sqlite-w32"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"
      PYTHON_HOME: "C:\\Python27"
    - TOX_ENV: "py27-sqlite-w32"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"
      PYTHON_HOME: "C:\\Python27-x64"
    - TOX_ENV: "py34-sqlite-w32"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "32"
      PYTHON_HOME: "C:\\Python34"
    - TOX_ENV: "py34-sqlite-w32"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "64"
      PYTHON_HOME: "C:\\Python34-x64"
    - TOX_ENV: "py35-sqlite-w32"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "32"
      PYTHON_HOME: "C:\\Python35"
    - TOX_ENV: "py35-sqlite-w32"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"
      PYTHON_HOME: "C:\\Python35-x64"
    - TOX_ENV: "py36-sqlite-w32"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "32"
      PYTHON_HOME: "C:\\Python36"
    - TOX_ENV: "py36-sqlite-w32"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
      PYTHON_HOME: "C:\\Python36-x64"
    - TOX_ENV: "py27-flake8"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"
      PYTHON_HOME: "C:\\Python27"
    - TOX_ENV: "py34-flake8"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "64"
      PYTHON_HOME: "C:\\Python34-x64"

install:
  # Ensure we use the right python version
  - "SET PATH=%PYTHON_HOME%;%PYTHON_HOME%\\Scripts;C:\\Program Files\\PostgreSQL\\9.5\\bin;%PATH%"
  - "SET TOXPYTHON=%PYTHON_HOME%\\python.exe"
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - "pip --version"
  - "pip install tox ppu"

# No build step - we don't have C extensions
build: false

test_script:
  - "tox -e %TOX_ENV%"

after_test:
  - "remove-old-files.py -o 180 %LOCALAPPDATA%\\pip\\Cache"
