#! /bin/sh

web="$HOME"/Internet/WWW/htdocs/phdru.name/Software/Python/mysql2sql/docs

cd "`dirname \"$0\"`"/docs/_build/html &&
rsync -ahP --del * --exclude=objects.inv "$web" &&

exec chmod -R u=rwX,go=rX "$web"
